@ParametersAreNonnullByDefault
@FieldsAreNonnullByDefault
@ReturnTypesAreNonnullByDefault
package com.miurasystems.examples.connectors;

import com.miurasystems.annotations.FieldsAreNonnullByDefault;
import com.miurasystems.annotations.ReturnTypesAreNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;
